version: "3"

services:
  front:
    image: swatigor17/codenames-frontend:1.0
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
      - app
    networks:
      - codenames-net
  app:
    image: swatigor17/codenames-backend:1.0
    container_name: app
    ports:
      - 8085:8085
    environment:
      - POSTGRES_DB=codenames
      - POSTGRES_HOST=db:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3752Amour
      - PG_DATA=/var/lib/postgresql/data
    restart: always
    depends_on:
      - db
    networks:
      - codenames-net
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3752Amour
      - POSTGRES_DB=codenames
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - codenames-net

volumes:
  postgresql:
  postgresql_data:
    driver: local

networks:
  codenames-net:
    driver: bridge