server:
  address: localhost
  port: 8080

spring:
  datasource:
    name: ${POSTGRES_DB:codenames}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:3752Amour}
    url:
      - jdbc:postgresql://${server.address}/${spring.datasource.name}

  jpa:
    show-sql: true
    generate-ddl: true

    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect

    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level %logger{15} - %msg%n'
  level:
    root: INFO
    logging.com.netcracker: TRACE
    com.netcraker.PropertyServiceDetailsRepository: DEBUG