server:
  port: 8085

spring:
  datasource:
    name: ${POSTGRES_DB:codenames}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:3752Amour}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${spring.datasource.name}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %-5level %logger{15} - %msg%n'
  level:
    root: INFO
    logging.com.netcracker: TRACE
    com.netcraker.PropertyServiceDetailsRepository: DEBUG

codenames:
  cors-allow-origin: ${CORS-ALLOW-ORIGIN:http://localhost:8080}